Add db in my MVP project
Andrey8705/full-stack-dev pull request #72
Opened 2024-12-30 01:54 UTC by Andrey8705

Добавляю в MVP проект базу данных.

2024-12-30 16:03 UTC, aissayev requested changes
For the MVP project you need to separate main file into sepaarte files for classes

2025-01-15 16:44 UTC, Andrey8705 commented
Код почти полностью переписан, классы и функции распределены по разным файлам. Обновлена структура проекта. Проверена работоспособность.

2025-01-15 17:18 UTC, aissayev approved these changes
Looks good to me, just remove the commented lines that are not used

2025-01-15 17:18 UTC, aissayev commented on MVP-project/backend/app/database/db_setup.py
> +#Base = declarative_base()
if not used remove

2025-01-15 17:18 UTC, aissayev commented on MVP-project/backend/app/functions/mainLogic.py
> +REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS"))
nice 💯

2025-01-15 17:18 UTC, aissayev commented on MVP-project/backend/app/functions/mainLogic.py
> +    #active_refresh_tokens[token_id] = {"email": email, "expires_at": expire}
is this uncommented line will be used? if not remove

2025-01-15 17:18 UTC, aissayev commented on MVP-project/backend/app/main.py
> +#Base.metadata.create_all(bind= engine)
remove this too if not used

2025-01-15 17:18 UTC, aissayev commented on MVP-project/backend/app/routers/userRouters.py
> +#from main import create_access_token, create_refresh_token, check_user_role, check_user_and_capsule_user_id, verify_acces_token
remove commented line

2025-01-15 18:04 UTC, aissayev approved these changes

2025-01-15 20:04 UTC, Andrey8705 commented on MVP-project/backend/app/functions/mainLogic.py
> +    #active_refresh_tokens[token_id] = {"email": email, "expires_at": expire}
Эта строка будет использоваться

2025-01-15 20:05 UTC, Andrey8705 commented on MVP-project/backend/app/main.py
> +#Base.metadata.create_all(bind= engine)
Хорошо

2025-01-15 20:05 UTC, Andrey8705 commented on MVP-project/backend/app/database/db_setup.py
> +#Base = declarative_base()
Ок

2025-01-15 20:05 UTC, merged